apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocddemo
  namespace: my-go-app-new
spec:
  project: default
  source:
    repoURL: https://github.com/raghavi101/argocd_demo.git
    targetRevision: HEAD
    path: simpleapp
  destination:
    server: https://kubernetes.default.svc
    namespace: my-go-app-new