apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-app-new
  template:
    metadata:
      labels:
        app: my-go-app-new
    spec:
      containers:
      - name: my-go-container-new
        image: raghavi101/my-go-app-new:mytag
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
